### ISSUE TITLE
column editor config issue

### ISSUE THREAD

**Issue by ebinjo13** [netzke/netzke-basepack#139]
column :user_id do |c|
    c.editor = {xtype: :combobox, editable: false, min_chars: 2}
end

It ismentioned in the doc that,

A hash that will override the automatic editor configuration. For example, for one-to-many association column you may set it to {min_chars: 1}, which will be passed to the combobox and make it query its remote data after entering 1 character (instead of default 4).

Seems {min_chars: 1} is not working

**Comment by mxgrn** [comment]
Solved in later versions, closing.
