### ISSUE TITLE
Decimal columns do not work properly in advanced search panel

### ISSUE THREAD

**Issue by mxgrn** [netzke/netzke-basepack#163]

**Comment by mxgrn** [comment]
Fixed in aca3d40

**Comment by elitwin** [comment]
Decimal columns work in the Extended search screen now with this commit.
However, float columns do not work.

Also, for the in-grid filter on a decimal column, if you enter more than 2 decimal places, the text box rounds the value to 2 decimals making the query not work for many values.

In the image below, I want to filter on "equals 3.875", but something is rounding/formatting the in-grid filter value to 3.88. (I can use the extended search and enter 3.875 without it rounding.)

![image](https://cloud.githubusercontent.com/assets/85953/7070543/804445ce-de94-11e4-952c-d511d0090de6.png)

**Comment by mxgrn** [comment]
These should be now fixed both in master and in 0-11.

**Comment by elitwin** [comment]
This fix works in master, but it doesn't look like the javascripts/basepack.js file for the 0-11 branch was modified with the fix.

This block is only in master:

    // Fix 2-digit precision in the numeric filter
    Ext.define('Ext.grid.filters.filter.Number', {
      override: 'Ext.grid.filters.filter.Number',
      getItemDefaults: function() {
        return Ext.apply(this.itemDefaults, { decimalPrecision: 20 });
      }
    });

**Comment by mxgrn** [comment]
Correct, sorry. Ext 4 required a slightly different patch. Released in 0.11.1.

**Comment by elitwin** [comment]
I realized the fix was in a different place after testing the 0.11.1 Github branch. Thanks for fixing this in the 0.11 branch.
