### ISSUE TITLE
don't run on master (but does on v0.12.0)

### ISSUE THREAD

**Issue by vindvaki** [netzke/netzke-basepack#164]
It would make contributions easier if the master branch was always usable. I just tried cloning netzke-basepack and ran `bundle install`, and it fails with 

    Could not find netzke-core-0.12.1 in any of the sources

Checking out v0.12.0 and doing the same gets me quite a bit further: The bundles install and the tests run green :)

**Comment by vindvaki** [comment]
For reference, the latest commit at the time of writing is `f50932cc6b97974cc2d7170fea7eb365e98cac20`

**Comment by mxgrn** [comment]
@vindvaki Thanks for pointing this out! I've updated all Netzke gems to use Github master as dev dependencies, and this should now be solved.
