### ISSUE TITLE
version.rb has 0.12.3 but latest released version is 0.12.6

### ISSUE THREAD

**Issue by vindvaki** [netzke/netzke-basepack#167]
See https://github.com/netzke/netzke-core/blob/master/lib/netzke/core/version.rb#L3

**Comment by mxgrn** [comment]
Yeah, Core and Basepack patch versions are not necessarily in sync. Are you having any issues with that?

**Comment by vindvaki** [comment]
No, not really. I was just wondering if it was by design.
