### ISSUE TITLE
cancancan

### ISSUE THREAD

**Issue by markmcdonald51** [netzke/netzke-basepack#174]
Hi!

Neat project. Would it be possible to use something like https://github.com/CanCanCommunity/cancancan with netzke?

Nice work!
--mark

**Comment by mxgrn** [comment]
Should totally be doable, as you can monkey-patch `Netzke::Base` in Rails initializer and add any method to that, like "can?"

**Comment by scho** [comment]
Back then, when I was using Netzke, I wrote this plugin: https://github.com/scho/netzke-cancan

**Comment by mxgrn** [comment]
Closing as not actionable.
