### ISSUE TITLE
simple_app this.mainPanel is null

### ISSUE THREAD

**Issue by blackbumer** [netzke/netzke-basepack#48]
Hello.
when i try use simple_app in extjs4 branch i got an javascript error

 this.mainPanel is null
(regarding firebug this.mainPanel.removeAll();  method in 

''' processHistory: function(token){
    if (token){
     this.mainPanel.removeAll();
     this.loadNetzkeComponent({name: token, container: this.mainPanel});
    } else {
     this.mainPanel.removeAll();
   }
  },

am i doing something wrong or is it a bug?

https://gist.github.com/1131795

**Comment by mxgrn** [comment]
Irrelevant by now, closing.
