### ISSUE TITLE
Gridpanels with 2 columns of same association type are busted

### ISSUE THREAD

**Issue by arman000** [netzke/netzke-basepack#61]
I have a model C with two associations/belongs_to of model T. i.e. C has two columns (fld1 and fld2) which hold ids of T.

When C is displayed in a Gridpanel with columns :fld1\_\_name and :fld2\_\_name, I get SQL exceptions when trying to sort using fld2 by clicking on the column header. I get similar errors with filtering.

I can provider further details or sample code if this report is not clear.

**Comment by mxgrn** [comment]
Should be fixed by now. Closing.
