### ISSUE TITLE
FormPanel ignores config[:record] when update is performed

### ISSUE THREAD

**Issue by scho** [netzke/netzke-basepack#64]
I'm about to create a form, in which a user can edit his profile. So I created a FormPanel with the following option:
```ruby
:record => Netzke::Core.current_user
```
This works great, but I found out, that when an update is preformed, this option will be ignored, due to this (See: https://github.com/skozlov/netzke-basepack/blob/master/lib/netzke/basepack/form_panel/services.rb#L105 ):
```ruby
@record ||= data_adapter.find_record hsh.delete(data_class.primary_key.to_s)
```
and the fact, that the record method (which sets @record from the config) was never called before.
So if a user sends a request with an id, different from the own id, it will update another users profile.

I could fix this issue by calling record explicitly in the create_or_update_record method:
```ruby
def create_or_update_record(hsh)
  record
  super
end
```

So is this some kind of 'bug' or is this component not meant to be to protect users from updating other objects, than the on in :record?

I also had to overwrite the netzke_load endpoint, in order to prevent users from loading other profiles.

If someone has an idea, how to fix this properly and could point me into directions, I could try to fix it and send a pull request.

**Comment by mxgrn** [comment]
Fixed by now. Closing.
